version: "0.1"
services:
  template-postgres:
    container_name: template-postgres
    image: template-postgres:0.1
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/initialize:/docker-entrypoint-initdb.d
    env_file:
      - database/docker.env
    ports:
      - 5432:5432
  
volumes:
  postgres_data: